# Generated by Django 4.1.5 on 2023-01-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.CharField(default='aynonomous', max_length=100),
        ),
    ]
